version: '3'

dotenv: ['.env']

vars:
  BINARY_NAME: api
  EXT: '{{if eq OS "windows"}}.exe{{end}}'

tasks:
  default:
    cmds:
      - task: run

  build:
    desc: Build the application
    cmds:
      - go build -o bin/{{.BINARY_NAME}}{{.EXT}} cmd/api/main.go

  run:
    desc: Run the application
    deps: [build]
    cmds:

      - ./bin/{{.BINARY_NAME}}{{.EXT}}

  seed:
    desc: Seed the database
    cmds:
      - go run cmd/seed/main.go

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  clean:
    desc: Clean binary files
    cmds:
      - cmd: rm -rf bin
        platforms: [linux, darwin] 
      
      - cmd: powershell Remove-Item -Recurse -Force bin
        platforms: [windows]     
        ignore_error: true

  docker:
      desc: Build and run with Docker Compose
      cmds:
        - docker compose up --build