version: '3'

dotenv: ['.env']

vars:
  BINARY_NAME: api
  DEFAULT_PORT: 3000

tasks:
  default:
    cmds:
      - task: run

  build:
    desc: Build the application
    cmds:
      - go build -o bin/{{.BINARY_NAME}}{{exeExt}} cmd/api/main.go
    vars:
      exeExt: '{{if eq OS "windows"}}.exe{{end}}'


  docker:
    desc: Build and run with Docker
    cmds:
      - echo "Building Docker image..."
      - docker build -t gotel-api .
      - echo "Running Docker container on port {{.HTTP_PORT}}..."
      - docker run -p {{.HTTP_PORT}}:{{.HTTP_PORT}} gotel-api
    vars:
      HTTP_PORT: '{{default .DEFAULT_PORT .HTTP_LISTEN_ADDRESS | replace ":" ""}}'

  clean:
    desc: Clean binary files
    cmds:
      - rm -rf bin
      - cmd: powershell Remove-Item -Recurse -Force bin
        platforms: [windows]