version: '3'
dotenv: ['.env']
vars:
  BINARY_NAME: api
  DEFAULT_PORT: 3000
tasks:
  default:
    cmds:
      - task: run

  build:
    desc: Build the application
    cmds:
      - go build -o bin/{{.BINARY_NAME}}{{exeExt}} cmd/api/main.go
    vars:
      exeExt: '{{if eq OS "windows"}}.exe{{end}}'

  run:
    desc: Run the application
    deps: [build] 
    cmds:
      - ./bin/{{.BINARY_NAME}}{{exeExt}}
    vars:
      exeExt: '{{if eq OS "windows"}}.exe{{end}}'

  seed:
    desc: Seed the database
    cmds:
      - go run cmd/seed/main.go

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...
  clean:
    desc: Clean binary files
    cmds:
      - rm -rf bin
      - cmd: powershell Remove-Item -Recurse -Force bin
        platforms: [windows]
docker:
    desc: Build and run with Docker
    cmds:
      - echo "Building Docker image..."
      - docker build -t gotel-api .
      - echo "Running Docker container on port {{.HTTP_PORT}}..."
      - docker run -p {{.HTTP_PORT}}:{{.HTTP_PORT}} gotel-api
    vars:
      HTTP_PORT: '{{default .DEFAULT_PORT .HTTP_LISTEN_ADDRESS | replace ":" ""}}'

